### ISSUE TITLE
Access AWS secrets via secrets CLI

### ISSUE THREAD

**Issue by matteozambon89** [glg-public/build-and-deploy-ecr#14]
Currently the only way to provide secrets to the Dockerfile during build is through the GitHub secrets which are hardcoded within the repository settings itself.

Might be also useful to allow access to the AWS secrets.

A scenario we encountered is when we need to access a private NPM package from the GitHub Package Registry.
We have deployed an NPM package to the registry which needs to be accessible when running `$ npm install`, the token is stored in AWS secrets manager in the `production` namespace with the name `GITHUB_DEPLOYMENT_USER_PACKAGE_REGISTRY_READ_TOKEN`, but we have found the only way to access this value during build and deployment of our ECR image is to hardcode the value into GitHub secrets and provide it through the `BUILD_CONFIG` variable.

Because we had to hardcode it, should somebody rotate the secret in the AWS secret manager our build would stop working.

**Comment by fearphage** [comment]
This is all to access GitHub's NPM repository, correct?

Why don't you install the packages directly from GitHub with `npm install glg/et-node-logger` instead? This is what the vast majority of apps do. This would remove your need for `secrets` access.

We have no plans to add `secrets` access to an external environment.

**Comment by fearphage** [comment]
More details about [deploying private packages directly from GitHub](https://github.com/glg/knowledgebase/discussions/48).

**Comment by matteozambon89** [comment]
@fearphage thanks for your suggestions. I understand security is probably the reason why there's no plan to allow `secrets` access outside of GLG.

The solution (link above) you provided is what we ended up doing for all current packages except the `et-node-logger`.

The main reason why the `et-node-logger` isn't installed via git URL is its dependency on `typescript`. We were also trying to avoid to build it on `postinstall` or adding the built code to the git history.

In my opinion there are many pros of having the `et-node-logger` as an npm package:
- automated building/publishing process via GitHub actions
- littler package payload (use of `.npmignore` during publishing)
- no building during `npm installl` (which would require dev dependencies to be installed on prod)
- easier to maintain, reduced conflicts on the `build` folder
- use of the standard npm versioning vs git branches/tags/releases

Would there be any benefit in having the `et-node-logger` installable via git URL rather than npm package?
