### ISSUE TITLE
The payload of github.context is not consistent when it's be used as a job

### ISSUE THREAD

**Issue by ddai1** [glg-public/build-and-deploy-ecr#44]
### What's happened
So far we don't have received any reports about this use case cause non of us has tried to use this in a scheduled github action.

We are trying to extract the information from github.context, but the payload will be changed into below example when this github action tool has been used in a scheduled github actions. 

```jq
Context {
  payload: { schedule: '0 14 * * 1-5' },
  eventName: 'schedule',
  sha: '724b2b6825cb678438a9bcfddd25e2296b4f9d8c',
  ref: 'refs/heads/gds',
  workflow: 'Scheduled Build Image and Push to ECR',
  action: '__glg-public_build-and-deploy-ecr',
  actor: 'ddai1',
  job: 'build-and-deploy',
  runNumber: 21,
  runId: 2934261[17](https://github.com/glg/knowledgebase/runs/8054779961?check_suite_focus=true#step:3:18)1,
  apiUrl: 'https://api.github.com/',
  serverUrl: 'https://github.com/',
  graphqlUrl: 'https://api.github.com/graphql'
}
```
### How to solve this
Environment variables is not more consistent in this use case, we can extract the information by using environment variables.
```javascript
const ref = process.env.GITHUB_REF;
const sha = process.env.GITHUB_SHA;
const ghRepo = process.env.GITHUB_REPOSITORY;
const repoName = ghRepo.match(/\/(.*)/)[1];

```

Below is the link of github action environment variables.
https://docs.github.com/en/actions/learn-github-actions/environment-variables 

### Caveat
Branch `know` is be used for `glg/knowledgebase` only, DO NOT merge any changes from `know` to `main`.

**Comment by igroff** [comment]
We've moved this repo into the glg org and made a ton of changes
